server:
  port: 8080
  servlet:
    context-path: /ElderHub

spring:
  application:
    name: elder-hub
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 注意：请把你本地数据库的密码修改到 password 这一行
    url: jdbc:mysql://localhost:3306/elderhub?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: auto
      table-prefix: t_